#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'rubygems'
require 'thrift'
require 'myfirst/myfirst_types'

module Myfirst
end
