#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'rubygems'
require 'thrift'

module Myfirst
  class MyError < ::Thrift::Exception
    include ::Thrift::Struct, ::Thrift::Struct_Union
    ERROR_CODE = 1
    ERROR_DESCRIPTION = 2

    FIELDS = {
      ERROR_CODE => {:type => ::Thrift::Types::I32, :name => 'error_code'},
      ERROR_DESCRIPTION => {:type => ::Thrift::Types::STRING, :name => 'error_description'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
